M48
; DRILL file {KiCad 7.0.2} date Wed Apr  3 12:52:35 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-03T12:52:35+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X4.2534Y-2.3142
X4.2534Y-2.5418
T2
X2.3814Y-1.6201
X2.6963Y-1.6201
T0
M30
